# -*- coding: utf-8 -*-
"""firststep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/131KujsUGpp14qP9woOdwk_Nkr6sLyiZP

## Armazenar variáveis
"""

nome = 'Rafael'
idade = 38
nome
idade

nome

print(nome, idade)



"""# Criando uma função"""

def saudacao():
  nome = input('Qual é o seu nome? ')
  print(f'Olá {nome}!')

saudacao()

"""# Criando um função com parâmetro"""

nome = 'Henrique'
def saudacao_com_parm(nome_da_pessoa):
  print(f'Olá {nome_da_pessoa}!')

saudacao_com_parm(nome)



"""# Condicional"""

idade = int(input('Qual sua idade? '))

def verifica_maioridade(idade):
  if idade >= 18:
    print('Permitido')
  else:
    print('Proibido')

verifica_maioridade(idade)

"""# Exercício: Cálculo da velocidade média"""

distancia = float(input('Digite a distância em metros entre os pontos A e B:'))
tempo = int(input('Digite o tempo percorrido em segundos: '))

def calcular_velocidade_media(espaco, tempo):
  v = distancia / tempo
  print(f'Velocidade: {v} m/s')

calcular_velocidade_media(distancia, tempo)



"""# Criando lista"""

idades = [10, 15, 20, 25, 30]
#         0    1   2   3   4
#         0   -4  -3  -2  -1

idades[0]

idades[-4]

idades[0:3]

idades[-1:]

idades[1:]

idades[:-1]



"""# Percorrendo uma lista"""

idades = [18, 38, 35, 10]

def verifica_maioridade_para_beber(idade):
  if idade >= 18:
    print(f'A idade é {idade} anos, então é PERMITIDO bebidas alcólicas')
  else:
    print(f'A idade é {idade} anos, então é PROIBIDO bebidas alcólicas')

for idade in idades:
  verifica_maioridade_para_beber(idade)

type(idades)



"""# Adicionando elementos em uma lista"""

idades = [10, 25, 17]
permissoes = []

def adicionar_condicao_booleano(lista):
  for idade in lista:
    if idade >= 18:
      permissoes.append(True)
    else:
      permissoes.append(False)

def verificar_permissoes(lista):
  if len(lista) == 0:
    print(f'Lista vazia')
  else:
    for permissao in lista:
      if permissao == True:
        print(f'Permitido')
      else:
        print(f'Proibido')

adicionar_condicao_booleano(idades)
verificar_permissoes(permissoes)

